### ISSUE TITLE
Number of users per WLAN

### ISSUE THREAD

**Issue by mausampaio** [zbx-sadman/unifi_miner#6]
Hello,

I would like to get the amount of users logged into a UAP over WLAN.

Is there any way to get this information?

Thank you!

**Comment by zbx-sadman** [comment]
Yes, you can get it, but not so simply.

UniFi controller does not have "wlan_name" or similar field in _user_ object record.

But object _uap_ have _vap\_table_ nested array (virtual AP, one per WLAN on UAP), that have _wlanconf\_id_ and _num\_sta_ fields. You must summarize _num\_sta_ field's values for all _vap\_table_ objects (on all Site's UAPs) that have _wlanconf\_id_ of required WLAN. 

So, at first you must take _wlanconf\_id_ of some WLAN:
`./unifi_miner.pl -a get -o wlan -s default -k [name=myWlanName]._id`
At second you must use this _wlanconf\_id_  to filter _vap\_table_ objects, and sum _num\_sta_ fields:
`./unifi_miner.pl -a sum -o uap -s default -k vap_table.[wlanconf_id=myWLANID].num_sta`

And, i think, that both of _unifi_miner.pl_ calls can be joined:
`./unifi_miner.pl -a sum -o uap -s default -k vap_table.[wlanconf_id=@./unifi_miner.pl -a get -o wlan -s default -k [name=myWlan]._id@].num_sta` (replace @ sign to backquote mark, Github just eat it in message).

If you use Zabbix - just add new prototype to "UniFi WLANs discovery" rule: _unifi.proxy[sum,uap,{#SITENAME},\"vap_table.[wlanconf\_id={#ID}].num_sta\"]_

Unfortunately, i can't test it, because does not have UniFi equipments at home. Try, and tell about result.

**Comment by mausampaio** [comment]
Very good! It worked perfectly, thank you very much.

I also tried using the -m parameter to return from a specific UAP and it worked perfectly.

Thank you for your great work, I'll help whenever i can.
